app/models/mooc.py
from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship
from app.models import Base


class MOOC(Base):
    """Represent an online course exists in a MOOC provider"""
    __tablename__ = 'mooc'

    id = Column(Integer, primary_key=True)
    title = Column(String(80), nullable=False)
    provider = Column(String(80), nullable=False)
    creator = Column(String(80))
    level = Column(String(32))
    url = Column(String(250))
    description = Column(String(250))
    image = Column(String(250))
    field_id = Column(Integer, ForeignKey('field.id'))
    field = relationship("Field")
    user_id = Column(Integer, ForeignKey('user.id'))
    user = relationship("User")

    @property
    def serialize(self):
        """Return object data in easily serializable format"""
        return {
            'id':           self.id,
            'title':        self.title,
            'provider':     self.provider,
            'creator':      self.creator,
            'level':        self.level,
            'description':  self.description,
            'url':          self.url,
            'image':        self.image,
            'field_id':     self.field_id
        }

app/views/auth.py
from app.models.user_helper import *

from flask import render_template, request, url_for,\
    redirect, jsonify, flash, Blueprint

from flask import session as login_session
import random
import string

from oauth2client.client import flow_from_clientsecrets
from oauth2client.client import FlowExchangeError
import httplib2
import requests
import json
from flask import make_response

from app import csrf

# OAuth client ID for Google
CLIENT_ID = json.loads(
    open('/var/www/catalog/client_secrets.json', 'r').read())['web']['client_id']

# OAuth APP ID and SECRET for Facebook
APP_ID = '1407391409368190'
APP_SECRET = '629a86589bbad38ab16ac6692967cac2'

auth = Blueprint('auth', __name__)


# Authentication & Authorization
@auth.route('/login/')
def show_login():
    """Show login page and Generate a random state token"""
    state = ''.join(random.sample(string.ascii_letters + string.digits, 32))
    login_session['state'] = state
    return render_template('login.html', STATE=state)


@auth.route('/gconnect', methods=['POST'])
@csrf.exempt
def gconnect():
    """Handle login authentication and authorization with Google"""
    # Validate state token
    if request.args.get('state') != login_session.get('state'):
        print('Invalid state parameter.')
        return jsonify(error={'msg': 'Invalid state parameter.'}), 401

    # Obtain authorization code
    code = request.data

    try:
        # Upgrade the authorization code into a credentials object
        oauth_flow = flow_from_clientsecrets('/var/www/catalog/client_secrets.json', scope='')
        oauth_flow.redirect_uri = 'postmessage'
        credentials = oauth_flow.step2_exchange(code)
    except FlowExchangeError:
        print('Failed to upgrade the authorization code.')
        return jsonify(error={
            'msg': 'Failed to upgrade the authorization code.'}), 401

    # Check that the access token is valid
    access_token = credentials.access_token
    url = ('https://www.googleapis.com/oauth2/v1/tokeninfo?access_token={}'
           .format(access_token))
    result = requests.get(url).json()

    # If there was an error in the access token info, abort
    if result.get('error') is not None:
        return jsonify(error={'msg': result.get('error')}), 500

    # Verify that the access token is used for the intended user
    gplus_id = credentials.id_token['sub']
    if result.get('user_id') != gplus_id:
        return jsonify(error={
            'msg': "Token's user ID doesn't match given user ID."}), 401

    # Verify that the access token is valid for this app.
    if result['issued_to'] != CLIENT_ID:
        print("Token's client ID does not match app's.")
        return jsonify(error={
            'msg': "Token's client ID does not match app's."}), 401

    # Verify if the user already connected
    stored_access_token = login_session.get('access_token')
    stored_gplus_id = login_session.get('gplus_id')
    if stored_access_token is not None and stored_gplus_id == gplus_id:
        # Update the access_token in login_session
        # to avoid error when signing out :)
        login_session['access_token'] = credentials.access_token
        response = make_response(
            json.dumps('Current user is already connected.'), 200)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Store the access token in the session for later use.
    login_session['access_token'] = credentials.access_token
    login_session['gplus_id'] = gplus_id

    # Get user info
    userinfo_url = "https://www.googleapis.com/oauth2/v1/userinfo"
    params = {'access_token': credentials.access_token, 'alt': 'json'}
    data = requests.get(userinfo_url, params=params).json()

    # Store user info in the current session
    login_session['provider'] = 'google'
    login_session['username'] = data['name']
    login_session['picture'] = data['picture']
    login_session['email'] = data['email']

    # Create a new user if it doesn't exist
    old_user = False  # Track if user logged in before
    user_id = get_user_id(login_session['email'])
    if user_id is None:
        # Create a new user
        user_id = create_user(login_session)
    else:
        old_user = True  # User in database so welcome back!
    login_session['user_id'] = user_id

    flash("You are now logged in as {}".format(login_session['username']))

    welcome = '''
    <div>
        <h2>Welcome, {}!</h2>
        <img src="{}" style="width: 200px; height: 200px;border-radius: 50%;">
    </div>
    '''
    welcome_back = '''
    <div>
        <h2>Welcome back, {}!</h2>
        <p>I remember you my friend :)</p>
        <img src="{}" style="width: 200px; height: 200px;border-radius: 50%;">
    </div>
    '''

    if old_user:
        return welcome_back.format(
            login_session['username'], login_session['picture'])

    return welcome.format(login_session['username'], login_session['picture'])


@auth.route('/gdisconnect/')
def gdisconnect():
    """Logout from Google Auth"""
    access_token = login_session.get('access_token')
    gplus_id = login_session.get('gplus_id')
    if gplus_id is None:
        print('Current user not connected.')
        return jsonify(error={'msg': 'Current user not connected.'}), 401

    # Revoke access of logged in user
    url = 'https://accounts.google.com/o/oauth2/revoke?token={}'.\
        format(access_token)
    h = httplib2.Http()
    result = h.request(url, 'GET')[0]
    if result['status'] == '200':
        del login_session['access_token']
        del login_session['gplus_id']
        del login_session['username']
        del login_session['email']
        del login_session['picture']
        del login_session['user_id']
        del login_session['provider']
        return jsonify(success={'msg': 'Successfully disconnected.'})

    return jsonify(error={
        'msg': 'Failed to revoke token for given user.'}), 400


@auth.route('/fbconnect', methods=['POST'])
@csrf.exempt
def fbconnect():
    """Handle login authentication and authorization with Facebook"""
    # Validate state token
    if request.args.get('state') != login_session.get('state'):
        print('Invalid state parameter.')
        return jsonify(error={'msg': 'Invalid state parameter.'}), 401

    # Obtain authorization token
    token = request.data.decode()

    url = 'https://graph.facebook.com/oauth/access_token?' \
          'grant_type=fb_exchange_token&client_id={}&client_secret={}' \
          '&fb_exchange_token={}'.format(APP_ID, APP_SECRET, token)
    result = requests.get(url).json()

    # Get access token from response
    access_token = result.get('access_token')

    # Verify if the user already connected
    if login_session.get('access_token') is not None:
        # Update the access_token in login_session
        # to avoid error when signing out :)
        login_session['access_token'] = access_token
        response = make_response(
            json.dumps('Current user is already connected.'), 200)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Use token to get user info from API
    url = 'https://graph.facebook.com/v2.8/me?access_token={}' \
          '&fields=name,id,email'.format(access_token)
    data = requests.get(url).json()

    login_session['provider'] = 'facebook'
    login_session['username'] = data["name"]
    login_session['email'] = data["email"]
    login_session['facebook_id'] = data["id"]

    # The token must be stored in the login_session in order to properly logout
    login_session['access_token'] = access_token

    # Get user picture
    url = 'https://graph.facebook.com/v2.8/me/picture?access_token={}' \
          '&redirect=0&height=200&width=200'.format(access_token)
    data = requests.get(url).json()
    login_session['picture'] = data["data"]["url"]

    # Create a new user if it doesn't exist
    old_user = False  # Track if user logged in before
    user_id = get_user_id(login_session['email'])
    if user_id is None:
        # Create a new user
        user_id = create_user(login_session)
    else:
        old_user = True  # User in database so welcome back!
    login_session['user_id'] = user_id

    flash("You are now logged in as {}".format(login_session['username']))

    welcome = '''
    <div>
        <h2>Welcome, {}!</h2>
        <img src="{}" style="width: 200px; height: 200px;border-radius: 50%;">
    </div>
    '''
    welcome_back = '''
    <div>
        <h2>Welcome back, {}!</h2>
        <p>I remember you my friend :)</p>
        <img src="{}" style="width: 200px; height: 200px;border-radius: 50%;">
    </div>
    '''
    if old_user:
        return welcome_back.format(
            login_session['username'], login_session['picture'])

    return welcome.format(login_session['username'], login_session['picture'])


@auth.route('/fbdisconnect/')
def fbdisconnect():
    """Logout from Facebook Auth"""
    facebook_id = login_session.get('facebook_id')

    # The access token must me included to successfully logout
    access_token = login_session.get('access_token')
    if facebook_id is None:
        print('Current user not connected.')
        return jsonify(error={'msg': 'Current user not connected.'}), 401

    url = 'https://graph.facebook.com/{}/permissions?access_token={}'\
        .format(facebook_id, access_token)
    result = requests.delete(url)
    # print('result by requests ', result.json())

    del login_session['facebook_id']
    del login_session['access_token']
    del login_session['username']
    del login_session['email']
    del login_session['picture']
    del login_session['user_id']
    del login_session['provider']
    return jsonify(success={'msg': 'Successfully disconnected.'}), 200


@auth.route('/disconnect')
def disconnect():
    """Logout from any oauth provider"""
    if 'provider' in login_session:
        if login_session.get('provider') == 'google':
            gdisconnect()

app/views/moocs.py
from app.models import session, Field, MOOC, User
from app.models.user_helper import *

from sqlalchemy import asc, desc

from flask import render_template, request, url_for,\
    redirect, jsonify, flash, Blueprint

from flask import session as login_session

from .decorators import login_required, category_exist, item_exist
mooc = Blueprint('mooc', __name__)


@mooc.route('/fields/<int:field_id>/')
@mooc.route('/fields/<int:field_id>/moocs/')
@category_exist
def show_moocs(field_id):
    """Show all MOOCs with a specific field"""
    field = session.query(Field).filter_by(id=field_id).first()
    fields = session.query(Field).order_by(asc(Field.name)).all()
    moocs = session.query(MOOC).filter_by(field_id=field_id)\
        .order_by(asc(MOOC.title)).all()
    creator = get_user_info(field.user_id)

    # Prevent unauthorized users from modification, They must login first
    if 'username' not in login_session:
        return render_template('public_moocs.html', field=field,
                               moocs=moocs, creator=creator, fields=fields)

    return render_template('moocs.html', field=field,
                           moocs=moocs, creator=creator, fields=fields)


@mooc.route('/fields/<int:field_id>/moocs/<int:mooc_id>/')
@item_exist
def show_mooc(field_id, mooc_id):
    """Show a MOOC"""
    field = session.query(Field).filter_by(id=field_id).first()
    mooc = session.query(MOOC).filter_by(id=mooc_id, field_id=field_id).first()

    # Prevent unauthorized users from modification, They must login first
    if 'username' not in login_session:
        return render_template('public_mooc.html', field=field, mooc=mooc)

    return render_template('mooc.html', field=field, mooc=mooc)


@mooc.route('/fields/<int:field_id>/moocs/new', methods=['GET', 'POST'])
@category_exist
@login_required
def new_mooc(field_id):
    """Add new MOOC"""
    field = session.query(Field).filter_by(id=field_id).first()

    if request.method == 'POST':
        if request.form.get('title') and request.form.get('provider') \
                and request.form.get('url'):
            mooc = MOOC(title=request.form.get('title'),
                        provider=request.form.get('provider'),
                        creator=request.form.get('creator'),
                        level=request.form.get('level'),
                        url=request.form.get('url'),
                        description=request.form.get('description'),
                        image=request.form.get('image'),
                        field=field, user_id=login_session.get('user_id'))
            session.add(mooc)
            session.commit()
            flash('New MOOC {} Successfully Created'.format(mooc.title))
        return redirect(url_for('mooc.show_moocs', field_id=field_id))

    return render_template('new_mooc.html', field=field)


@mooc.route('/fields/<int:field_id>/moocs/<int:mooc_id>/edit',
            methods=['GET', 'POST'])
@item_exist
@login_required
def edit_mooc(field_id, mooc_id):
    """Edit a MOOC"""
    field = session.query(Field).filter_by(id=field_id).first()
    mooc = session.query(MOOC).filter_by(id=mooc_id, field_id=field_id).first()

    # Verify if he is the user who created it
    if mooc.user_id == login_session['user_id']:
        if request.method == 'POST':
            if request.form.get('title'):
                mooc.title = request.form.get('title')
            if request.form.get('provider'):
                mooc.provider = request.form.get('provider')
            if request.form.get('creator'):
                mooc.creator = request.form.get('creator')
            if request.form.get('level'):
                mooc.level = request.form.get('level')
            if request.form.get('url'):
                mooc.url = request.form.get('url')
            if request.form.get('description'):
                mooc.description = request.form.get('description')
            if request.form.get('image'):
                mooc.image = request.form.get('image')
            session.add(mooc)
            session.commit()
            flash('MOOC {} Successfully Edited'.format(mooc.title))
            return redirect(url_for('mooc.show_moocs', field_id=field_id))

        return render_template('edit_mooc.html', mooc=mooc, field=field)
    else:
        return jsonify(error={'msg': "You are not the owner of that!!"}), 401


@mooc.route('/fields/<int:field_id>/moocs/<int:mooc_id>/delete',
            methods=['GET', 'POST'])
@item_exist
@login_required
def delete_mooc(field_id, mooc_id):
    """Delete a MOOC"""

    field = session.query(Field).filter_by(id=field_id).first()
    mooc = session.query(MOOC).filter_by(id=mooc_id, field_id=field_id).first()

    # Verify if he is the user who created it
    if mooc.user_id == login_session['user_id']:
        if request.method == 'POST':
            session.delete(mooc)
            session.commit()
            flash('MOOC {} Successfully Deleted'.format(mooc.title))
            return redirect(url_for('mooc.show_moocs', field_id=field_id))

        return render_template('delete_mooc.html', mooc=mooc, field=field)
    else:
        return jsonify(error={'msg': "You are not the owner of that!!"}), 401

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='favicon-test.ico') }}"/>
    <title>Top MOOC App</title>

    <!-- CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    {% block links %}{% endblock %}
</head>
<body>
    <!-- Header -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand my-brand" href="{{ url_for('field.index') }}"><img src="{{ url_for('static', filename='img/brand_test.png') }}" alt="logo" width="40px" style="display: inline">Top MOOC App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('field.index') }}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>  Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if 'username' in session %}
                    <li><a>{{ session.get('username') }}</a></li>
                    <li class="user-photo"><img src="{{ session.get('picture') }}" width="50px" style="border-radius: 50%;"></li>
                    <li class="login-btn"><a href="{{ url_for('auth.disconnect') }}" style="color: #FFFFFF;">Logout</a></li>
                    {% else %}
                    <li class="login-btn"><a href="{{ url_for('auth.show_login') }}" style="color: #FFFFFF;">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

        {% block content %}
        {% endblock %}

    <div class="container">
        <div class="row alert alert-warning text-center" style="margin-top: 30px" role="alert">
            <strong>Warning!</strong> App is under construction, if you found any bug please report us.
        </div>
    </div>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <p class="email"><i class="fa fa-envelope-o" aria-hidden="true"></i>&nbsp; ali.mahmoud@engineer.com</p>
                </div>
                <div class="col-sm-6 text-right social">
                    <a href="https://www.linkedin.com/in/alimahmoud7" target="_blank"><span class="fa fa-linkedin-square fa-3x" aria-hidden="true"></span></a>
                    <a href="https://github.com/AliMahmoud7" target="_blank"><span class="fa fa-github-square fa-3x" aria-hidden="true"></span></a>
                    <a href="https://twitter.com/Ali_Mahmoud_7" target="_blank"><span class="fa fa-twitter-square fa-3x" aria-hidden="true"></span></a>
                    <a href="https://www.facebook.com/Ali.Mahmoud.7" target="_blank"><span class="fa fa-facebook-square fa-3x" aria-hidden="true"></span></a>
                </div>
            </div>
            <div class="row text-center">
                <p class="copyright">Copyright &copy; 2017 Ali Mahmoud</p>
            </div>

        </div>
    </footer>

    <!-- JavaScript -->
    <script src="{{ url_for('static', filename='js/jquery-3.2.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

app/templates/delete_field.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h3 class="title">Are you sure you want to delete {{ field.name }} Field and all MOOCs inside it?</h3>
<form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <button class="btn btn-danger" type="submit">Delete</button>
    <a class="btn btn-default" href="{{ url_for('field.edit_field', field_id=field.id) }}">Edit</a>
    <a class="btn btn-default" href="{{ url_for('mooc.show_moocs', field_id=field.id) }}">Cancel</a>
</form>
</div>
{% endblock %}

app/templates/delete_mooc.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<h3 class="title">Are you sure you want to delete {{ mooc.title }}?</h3>
<form method="post" >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <button class="btn btn-danger" type="submit">Delete</button>
    <a class="btn btn-default" href="{{ url_for('mooc.edit_mooc', field_id=field.id, mooc_id=mooc.id) }}">Edit</a>
    <a class="btn btn-default" href="{{ url_for('mooc.show_moocs', field_id=field.id) }}">Cancel</a>
</form>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
    <div>
	{% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
			<div class="alert alert-success alert-dismissible text-center" role="alert">
  				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<strong>Well done!</strong> {{ message }}
			</div>
        {% endfor %}
        {% endif %}
    {% endwith %}
    </div>
<div class="row">
    <div class="col-sm-3">
        <h3>CS Fields</h3>
        <ul class="field-list">
            <li id="all-fields" class="active"><a href="{{ url_for('field.index') }}">All</a></li>
            {% for field in fields %}
            <li><a href="{{ url_for('mooc.show_moocs', field_id=field.id) }}">{{ field.name }}</a></li>
            {% endfor %}
        </ul>
        <a class="btn btn-default mooc-btn" href="{{ url_for('field.new_field') }}">Add Field</a>
    </div>

    {% block moocs %}
    <div class="col-sm-9 moocs">
        <div class="row field-header">
            <h3 class="title">Latest MOOCs</h3>
        </div>

        {%- for mooc in moocs %}
        <div class="row mooc">
            <div class="col-sm-3">
                <a href="{{ url_for('mooc.show_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}"><img src="{{ mooc.image }}" width="160px" class="mooc-img"></a>
            </div>
            <div class="col-sm-9 data">
                <div class="row">
                    <div class="col-sm-8">
                        <a href="{{ url_for('mooc.show_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}" class="mooc-title">{{ mooc.title }}</a>
                    </div>
                    <div class="col-sm-4">
                        {{ mooc.level }}
                    </div>
                </div>
                <div class="row" style="padding-top: 15px">
                    <div class="col-sm-8">
                        <strong>{{ mooc.field.name }}</strong>
                    </div>
                    <div class="col-sm-4">
                        <a href="{{ mooc.url }}">{{ mooc.provider }}</a>
                    </div>
                </div>
            </div>
        </div>
        {%- endfor %}
    </div>
    {% endblock %}
</div>
</div>
{% endblock %}

app/templates/mooc.html
{% extends "base.html" %}
{% block content %}
<div class="container">
<div class="row mooc">
    <div class="col-sm-8">
        <h3>{{ mooc.title }}</h3>
    </div>
    <div class="col-sm-4">
        <h4>{{ field.name }}</h4>
    </div>
</div>
<div class="row mooc">
    <div class="col-sm-8 desc">
        <p><strong>Description:</strong> {{ mooc.description }}</p>
    </div>
    <div class="col-sm-3">
        <div class="row">
            {{ mooc.level }}
        </div>
        <div class="row">
            {{ mooc.creator }}
        </div>
        <div class="row">
            <a href="{{ mooc.url }}">Go to MOOC</a>
        </div>

    </div>

</div>
{% if mooc.user_id == session.get('user_id') %}
<div class="row mooc">
    <a class="btn btn-default mooc-btn" href="{{ url_for('mooc.edit_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}">Edit</a>
    <a class="btn btn-danger mooc-btn danger" href="{{ url_for('mooc.delete_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}">Delete</a>
</div>
{% endif %}
</div>
{% endblock %}

app/templates/moocs.html
{% extends "index.html" %}
{% block moocs %}
<div class="col-sm-9 moocs">
    <div class="row field-header">
        <div class="col-sm-10">
            <h3>{{ field.name }}</h3>
            {% if creator.id == session.get('user_id') %}
            <a class="btn btn-default mooc-btn" href="{{ url_for('field.edit_field', field_id=field.id) }}">Edit</a>
            <a class="btn btn-danger mooc-btn danger" href="{{ url_for('field.delete_field', field_id=field.id) }}">Delete</a>
            {% endif %}
        </div>
        <figure class="col-sm-2 text-center">
                <img src="{{ creator.picture }}" alt="User who created this field" class="creator-img">
                <figcaption style="font-size: 14px">{{ creator.name }}</figcaption>
        </figure>
    </div>
    <a class="btn btn-default mooc-btn" href="{{ url_for('mooc.new_mooc', field_id=field.id) }}">Add MOOC</a>

    {%- for mooc in moocs %}
    <div class="row mooc">
        <div class="col-sm-3">
            <a href="{{ url_for('mooc.show_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}"><img src="{{ mooc.image }}" width="160px" class="mooc-img"></a>
        </div>
        <div class="col-sm-9 data">
            <div class="row">
                <div class="col-sm-8">
                    <a href="{{ url_for('mooc.show_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}" class="mooc-title">{{ mooc.title }}</a>
                </div>
                <div class="col-sm-4">
                    <img src="{{ user_info(mooc.user_id).picture }}" alt="User who created this mooc" width="50px">
                </div>
            </div>
            <div class="row extend">
                <div class="col-sm-8">
                    <strong>Creator:</strong> {{ mooc.creator }}
                </div>
                <div class="col-sm-4">
                     <a href="{{ mooc.url }}">{{ mooc.provider }}</a>
                </div>
            </div>
            {% if mooc.user_id == session.get('user_id') %}
            <div class="row">
                <div class="col-sm-12 extend">
                    <a class="btn btn-default mooc-btn" href="{{ url_for('mooc.edit_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}">Edit</a>
                    <a class="btn btn-danger mooc-btn danger" href="{{ url_for('mooc.delete_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}">Delete</a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    {%- endfor %}
</div>
{% endblock %}

app/templates/public_index.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
    <div>
	{% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
			<div class="alert alert-success alert-dismissible text-center" role="alert">
  				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<strong>Well done!</strong> {{ message }}
			</div>
        {% endfor %}
        {% endif %}
    {% endwith %}
    </div>
<div class="row">
    <div class="col-sm-3">
        <h3>CS Fields</h3>
        <ul class="field-list">
            <li id="all-fields" class="active"><a href="{{ url_for('field.index') }}">All</a></li>
            {% for field in fields %}
            <li><a href="{{ url_for('mooc.show_moocs', field_id=field.id) }}">{{ field.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

    {% block moocs %}
    <div class="col-sm-9 moocs">
       <div class="row field-header">
            <h3 class="title">Latest MOOCs</h3>
        </div>

        {%- for mooc in moocs %}
        <div class="row mooc">
            <div class="col-sm-3">
                <a href="{{ url_for('mooc.show_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}"><img src="{{ mooc.image }}" width="160px" class="mooc-img"></a>
            </div>
            <div class="col-sm-9 data">
                <div class="row">
                    <div class="col-sm-8">
                        <a href="{{ url_for('mooc.show_mooc', field_id=mooc.field.id, mooc_id=mooc.id) }}" style="font-size: 18px; text-decoration: none">{{ mooc.title }}</a>
                    </div>
                    <div class="col-sm-4">
                        {{ mooc.level }}
                    </div>
                </div>
                <div class="row" style="padding-top: 15px">
                    <div class="col-sm-8">
                        <strong>{{ mooc.field.name }}</strong>
                    </div>
                    <div class="col-sm-4">
                        <a href="{{ mooc.url }}">{{ mooc.provider }}</a>
                    </div>
                </div>
            </div>
        </div>
        {%- endfor %}
    </div>
    {% endblock %}
</div>
</div>
{% endblock %}